#!/bin/bash

parse_funs() {
  grep -oP "(?<=^exe_)\w+" "$0"
}

show_menu() {
  local options=("$@")
  local PS3="Choose a function to execute: "

  select opt in "${options[@]}"; do
    if [[ -n $opt ]]; then
      echo "Executing $opt..."
      # remove color codes
      opt=$(echo "$opt" | sed -r 's/\x1B\[[0-9;]*[JKmsu]//g')
      exe_$opt
      break
    else
      echo "Invalid option, please try again."
    fi
  done
}

parse_docstring() {
  # grep -oP "(?<=^# )[^\n]+"
  echo "$(grep -A1 -P "^exe_$1" "$0" | tail -n1)"
}

exe_example_function() {
  # This is an example function
  echo "Hello, World!"
}

exe_example_function2() {
  # This is another example function
  echo "Hello, World!"
}

if [[ $# -eq 0 ]]; then
  funs=($(parse_funs))
  funs_docstrings=()
  for fun in "${funs[@]}"; do
    funs_docstrings+=("$(echo -e "\e[92m$fun\e[0m") - $(parse_docstring "$fun")")
  done
  show_menu "${funs_docstrings[@]}"
else
  command="exe_$1"
  if type "$command" &>/dev/null; then
    shift
    "$command" "$@"
  else
    echo "Unknown function: $1"
    exit 1
  fi
fi
